group_only_message = "I only work in group chats."
start_message = "Hello!"
language_changed = "Language changed to English."
error_processing_image = "Sorry, an error occurred while processing the image. Please try again later."
failed_to_get_image_info = "Sorry, failed to get information about the image."
message_deleted_nsfw = "Your message will be deleted due to exceeding NSFW threshold {qe_value} > {qe_threshold}"
message_deleted_banned_tag = "Your message will be deleted due to a banned tag: {tag} ({score:.2f} > {tag_threshold})"
image_ratings = "Image ratings:"
image_tags = "Tags:"
new_qe_threshold_set = "New qe_threshold set: {new_threshold}"
please_specify_value_between = "Please specify a value between 0 and 1."
please_specify_correct_value = "Please specify a correct numerical value."
new_tag_threshold_set = "New tag_threshold set: {new_threshold}"
tag_added_to_banned = "Tag '{new_tag}' added to the banned list."
tag_already_in_banned = "Tag '{new_tag}' is already in the banned list."
please_specify_tag_to_add = "Please specify a tag to add."
tag_removed_from_banned = "Tag '{tag_to_remove}' removed from the banned list."
tag_not_found_in_banned = "Tag '{tag_to_remove}' not found in the banned list."
please_specify_tag_to_remove = "Please specify a tag to remove."
admin_only_command = "This command is only available to administrators."
