group_only_message = "Я работаю только в групповых чатах."
start_message = "Привет!"
language_changed = "Язык изменен на русский."
error_processing_image = "Извините, произошла ошибка при обработке изображения. Попробуйте позже."
failed_to_get_image_info = "Извините, не удалось получить информацию об изображении."
message_deleted_nsfw = "Ваше сообщение будет удалено из-за превышения NSFW {qe_value} > {qe_threshold}"
message_deleted_banned_tag = "Ваше сообщение будет удалено из-за запрещенного тега: {tag} ({score:.2f} > {tag_threshold})"
image_ratings = "Рейтинги изображения:"
image_tags = "Теги:"
new_qe_threshold_set = "Новый порог qe_threshold установлен: {new_threshold}"
please_specify_value_between = "Пожалуйста, укажите значение от 0 до 1."
please_specify_correct_value = "Пожалуйста, укажите корректное числовое значение."
new_tag_threshold_set = "Новый порог tag_threshold установлен: {new_threshold}"
tag_added_to_banned = "Тег '{new_tag}' добавлен в список запрещенных."
tag_already_in_banned = "Тег '{new_tag}' уже в списке запрещенных."
please_specify_tag_to_add = "Пожалуйста, укажите тег для добавления."
tag_removed_from_banned = "Тег '{tag_to_remove}' удален из списка запрещенных."
tag_not_found_in_banned = "Тег '{tag_to_remove}' не найден в списке запрещенных."
please_specify_tag_to_remove = "Пожалуйста, укажите тег для удаления."
admin_only_command = "Эта команда доступна только администраторам."